// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/carlos19960601/fiber-boilerplate/internal/pkg/app"
	"github.com/carlos19960601/fiber-boilerplate/internal/pkg/config"
	"github.com/carlos19960601/fiber-boilerplate/internal/repository"
	"github.com/carlos19960601/fiber-boilerplate/internal/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewWire(cfg *config.Config) (*app.App, func(), error) {
	db := repository.NewDB(cfg)
	migrate := server.NewMigrate(db)
	appApp := newApp(migrate)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)

var serverSet = wire.NewSet(server.NewMigrate)

func newApp(migrate *server.Migrate) *app.App {
	return app.NewApp(app.WithServer(migrate))
}
